### PR TITLE
Re-built initialisation data

### PR DESCRIPTION
**Pull request by viv**
- Added MUC rooms to XMPP 2
- Fixed TLS certs to match hostnames
- Renamed XMPP 2 users user3 and user4 (instead of user1 and user2)

### CODE REVIEW

**Comment by guusdk** [comment]
The two new MUCs pop up as expected on `xmpp2` - the users on `xmpp2` have also been renamed as you indicated.

However, the identity store on both servers still show the old certificate (covering `localhost.example` instead of the expected `xmpp1/xmpp2.localhost.example`)
image

**Comment by guusdk** [comment]
As a new feature request: would it be possible to enable "Allow peer certificates to be self-signed" on both servers, for server-to-server communication?

image

**Comment by viv** [comment]
I checked that the certificates had been updated before I pushed, not sure what's happening there maybe trashing your _data directory and running again would work, though the script already does that. I'll check again tomorrow and add the peer-cert self sign option.

**Comment by guusdk** [comment]
Certificates are now as-expected. I trashed _data and rebased to master. Unsure if either is needed.

**Pull request merged**
