### PR TITLE
Restructure Repository

### PR DESCRIPTION
**Pull request by Fishbowler**
Separate resources into separate folders

* Easier to add new variants and examples
* Simpler scripts

### CODE REVIEW

**Comment by guusdk** [comment]
Does it make sense to allow for this?

```$ ./federation/start.sh 
Starting a federated environment.
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-federated.yml'
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-federated.yml'
cp: cannot stat 'xmpp': No such file or directory
cp: cannot stat 'plugins': No such file or directory
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-federated.yml'
```

**Comment by guusdk** [comment]
Using the 'federated' startup, I can't retrieve the logs with the `get_logs.sh` script any longer. There is a small difference in the file name that's being searched for (note the `_` vs `.` character used at the end of the file name):

```$ cat scripts/get_logs.sh 
#!/bin/bash
CONTAINER_ONE=$(docker ps --filter status=running --format "{{.Names}}" | grep -E openfire-docker.+xmpp1.1)
CONTAINER_TWO=$(docker ps --filter status=running --format "{{.Names}}" | grep -E openfire-docker.+xmpp2.1)
CONTAINER_THREE=$(docker ps --filter status=running --format "{{.Names}}" | grep -E openfire-docker.+xmpp3.1)
CONTAINER_OTHER=$(docker ps --filter status=running --format "{{.Names}}" | grep -E openfire-docker.+otherxmpp.1)

[ -n "$CONTAINER_ONE" ] && docker exec -t "$CONTAINER_ONE" cat /usr/local/openfire/logs/openfire.log > 1-openfire.log
[ -n "$CONTAINER_TWO" ] && docker exec -t "$CONTAINER_TWO" cat /usr/local/openfire/logs/openfire.log > 2-openfire.log
[ -n "$CONTAINER_THREE" ] && docker exec -t "$CONTAINER_THREE" cat /usr/local/openfire/logs/openfire.log > 3-openfire.log
[ -n "$CONTAINER_OTHER" ] && docker exec -t "$CONTAINER_OTHER" cat /usr/local/openfire/logs/openfire.log > other-openfire.log
$ docker ps --filter status=running --format "{{.Names}}"
openfire_xmpp1_1
openfire_xmpp2_1
openfire_dozzle_1
openfire_db2_1
openfire_db1_1
```


@evdherberg had something very similar a few months ago, that kind of disappeared. We didn't look into it any further back then, I believe.

**Comment by Fishbowler** [comment]
The dot went in as regex to match `_` or `-`, which varied depending on your version of docker compose.

I think the real problem is the prefix - `openfire` vs `openfire-docker`.

Good catch! You'd think I'd tested more of these...

**Comment by guusdk** [comment]
Also, I think the `stop` script is not working or should be copied to each directory?

**Comment by Fishbowler** [comment]
> Does it make sense to allow for this?

Yes, absolutely. Fixed.

> I can't retrieve the logs with the get_logs.sh script any longer

Fixed, and a few others that I missed too :facepalm: 

> I think the stop script is not working

Works on my machine. What's the output?

**Comment by guusdk** [comment]
Stopping things still gives me an issue. Full example:

```
guus@octarine:~/SourceCode/GoodBytes/Surevine/openfire-docker-compose$ ./federation/start.sh 
Starting a federated environment.
~/SourceCode/GoodBytes/Surevine/openfire-docker-compose/federation ~/SourceCode/GoodBytes/Surevine/openfire-docker-compose
Removing network openfire_openfire-federated-net
WARNING: Network openfire_openfire-federated-net not found.
Removing network openfire_default
WARNING: Network openfire_default not found.
Pulling db1    ... done
Pulling db2    ... done
Pulling xmpp1  ... 
Pulling xmpp1  ... done
Pulling dozzle ... done
Pulling xmpp2  ... done
ERROR: 404 Client Error: Not Found ("pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
Creating network "openfire_openfire-federated-net" with driver "bridge"
Creating network "openfire_default" with the default driver
Creating openfire_db1_1    ... done
Creating openfire_db2_1    ... done
Creating openfire_dozzle_1 ... done
Creating openfire_xmpp2_1  ... done
Creating openfire_xmpp1_1  ... done
~/SourceCode/GoodBytes/Surevine/openfire-docker-compose
guus@octarine:~/SourceCode/GoodBytes/Surevine/openfire-docker-compose$ ./stop.sh 
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**Comment by guusdk** [comment]
Every start seems to output the directory in which things got started? Not much of a problem, but it feels like debug output to me?

See last line:
```bash
guus@octarine:~/SourceCode/GoodBytes/Surevine/openfire-docker-compose$ ./federation/start.sh 
Starting a federated environment.
~/SourceCode/GoodBytes/Surevine/openfire-docker-compose/federation ~/SourceCode/GoodBytes/Surevine/openfire-docker-compose
Removing network openfire_openfire-federated-net
WARNING: Network openfire_openfire-federated-net not found.
Removing network openfire_default
WARNING: Network openfire_default not found.
Pulling db1    ... done
Pulling db2    ... done
Pulling xmpp1  ... 
Pulling xmpp1  ... done
Pulling dozzle ... done
Pulling xmpp2  ... done
ERROR: 404 Client Error: Not Found ("pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
Creating network "openfire_openfire-federated-net" with driver "bridge"
Creating network "openfire_default" with the default driver
Creating openfire_db1_1    ... done
Creating openfire_db2_1    ... done
Creating openfire_dozzle_1 ... done
Creating openfire_xmpp2_1  ... done
Creating openfire_xmpp1_1  ... done
~/SourceCode/GoodBytes/Surevine/openfire-docker-compose
```

**Comment by Fishbowler** [comment]
@guusdk I've quietened the popd output. 

I've unified the stopping between what occurs in the start scripts, and what occurs in the stop script, by having the former call the latter. But that's probably going to exacerbate your problem. Can you do me a `docker-compose -v` and a `docker compose version`? I get v2.3.3 for both. This is what I see:

```
dan@dan-HP-ENVY-Laptop-17-ch0xxx:~/git/openfire-docker-compose$ ./federation/start.sh 
Starting a federated environment.
[+] Running 1/0
 ⠿ openfire  Warning: No resource found to remove                                                                                                                                                                                     0.0s
[+] Running 3/5
 ⠿ xmpp2 Error                                                                                                                                                                                                                        1.6s
 ⠿ xmpp1 Error                                                                                                                                                                                                                        1.6s
 ⠿ dozzle Pulled                                                                                                                                                                                                                      1.3s
 ⠿ db1 Pulled                                                                                                                                                                                                                         1.2s
 ⠿ db2 Pulled                                                                                                                                                                                                                         1.3s
Pulling xmpp1: Error response from daemon: pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling xmpp2: Error response from daemon: pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[+] Running 7/7
 ⠿ Network openfire_openfire-federated-net  Created                                                                                                                                                                                   0.0s
 ⠿ Network openfire_default                 Created                                                                                                                                                                                   0.0s
 ⠿ Container openfire_db1_1                 Started                                                                                                                                                                                   0.7s
 ⠿ Container openfire_db2_1                 Started                                                                                                                                                                                   0.6s
 ⠿ Container openfire_dozzle_1              Started                                                                                                                                                                                   0.6s
 ⠿ Container openfire_xmpp1_1               Started                                                                                                                                                                                   0.9s
 ⠿ Container openfire_xmpp2_1               Started                                                                                                                                                                                   0.9s
dan@dan-HP-ENVY-Laptop-17-ch0xxx:~/git/openfire-docker-compose$ ./stop.sh 
[+] Running 7/7
 ⠿ Container openfire_dozzle_1              Removed                                                                                                                                                                                   0.2s
 ⠿ Container openfire_xmpp2_1               Removed                                                                                                                                                                                  10.4s
 ⠿ Container openfire_xmpp1_1               Removed                                                                                                                                                                                  10.4s
 ⠿ Container openfire_db2_1                 Removed                                                                                                                                                                                   0.2s
 ⠿ Container openfire_db1_1                 Removed                                                                                                                                                                                   0.3s
 ⠿ Network openfire_default                 Removed                                                                                                                                                                                   0.3s
 ⠿ Network openfire_openfire-federated-net  Removed                                 
```

**Comment by Fishbowler** [comment]
Any better with explicitly using the new style commands?

**Comment by guusdk** [comment]
Eek. Things now seem properly broken.

```
$ ./federation/start.sh 
Starting a federated environment.
unknown shorthand flag: 'p' in -p
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/home/guus/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker
                           context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/guus/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/guus/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/guus/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

unknown flag: --env-file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/home/guus/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker
                           context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/guus/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/guus/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/guus/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

unknown flag: --env-file
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default "/home/guus/.docker")
  -c, --context string     Name of the context to use to connect to the daemon (overrides DOCKER_HOST env var and default context set with "docker
                           context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default "/home/guus/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default "/home/guus/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default "/home/guus/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a running container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesystem
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by default)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit codes

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go/guides/

/home/guus/SourceCode/GoodBytes/Surevine/openfire-docker-compose/federation/../_common/functions.sh: line 8: popd: directory stack empty
```

**Comment by guusdk** [comment]
Removing the Ubuntu-provided docker installation, replacing it with what's provided by the Docker project itself solved the above issue. I've followed https://docs.docker.com/engine/install/ubuntu/

As an aside: /me waves angry fist at inconsistent distribution maintenance.

**Comment by guusdk** [comment]
The `start` and `stop` output look sufficiently clean to me now.

On first glance, the environment (at least the clustering one) seems functional.

```
$ ./cluster/start.sh 
Starting a clustered environment.
Warning: No resource found to remove for project "openfire".
[+] Running 3/6
 ⠿ xmpp2 Error                                                                                                                                             1.6s
 ⠿ xmpp1 Error                                                                                                                                             1.6s
 ⠿ dozzle Pulled                                                                                                                                           1.3s
 ⠿ xmpp3 Error                                                                                                                                             1.6s
 ⠿ db Pulled                                                                                                                                               1.2s
 ⠿ lb Pulled                                                                                                                                               1.3s
Pulling xmpp1: Error response from daemon: pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling xmpp3: Error response from daemon: pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Pulling xmpp2: Error response from daemon: pull access denied for openfire, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[+] Running 8/8
 ⠿ Network openfire_openfire-clustered-net  Created                                                                                                        0.0s
 ⠿ Network openfire_default                 Created                                                                                                        0.0s
 ⠿ Container openfire-lb-1                  Started                                                                                                        0.7s
 ⠿ Container openfire-db-1                  Started                                                                                                        0.8s
 ⠿ Container openfire-dozzle-1              Started                                                                                                        0.5s
 ⠿ Container openfire-xmpp3-1               Started                                                                                                        1.4s
 ⠿ Container openfire-xmpp1-1               Started                                                                                                        1.2s
 ⠿ Container openfire-xmpp2-1               Started     
```
```
$ ./stop.sh 
[+] Running 8/8
 ⠿ Container openfire-dozzle-1              Removed                                                                                                        0.4s
 ⠿ Container openfire-xmpp1-1               Removed                                                                                                        1.1s
 ⠿ Container openfire-xmpp2-1               Removed                                                                                                        0.9s
 ⠿ Container openfire-lb-1                  Removed                                                                                                        0.8s
 ⠿ Container openfire-xmpp3-1               Removed                                                                                                        1.0s
 ⠿ Container openfire-db-1                  Removed                                                                                                        0.3s
 ⠿ Network openfire_default                 Removed                                                                                                        0.2s
 ⠿ Network openfire_openfire-clustered-net  Removed  
```

**Review by guusdk — APPROVED** [review]

**Comment by guusdk** [comment]
I have not checked if this flags missing docker dependencies (as I rather not want to mess up my installation), but I've verified that it runs with no issues with what I have installed now.

**Comment by guusdk** [comment]
After the last three commits, the environments still start up as expected. @Fishbowler promised me that he was done now, so I'll merge this, before he changes his mind. :)

**Pull request merged**
